export const languages = [
  {
    ERROR: "Ошибка",
    ERROR_ACCESS_TOKEN: "Ошибка токена доступа",
    INPUT_DATA: "Введите данные",
    LOADING: "Загрузка...",
    LOGIN: "Вход",
    REGISTER: "Регистрация",
    INVALID_LOGIN: "Вы ввели неправильный email или пароль",
    NO_ACCESS: "Нет доступа",
    SUCCESFULLY_ENTERED: "Вы успешно вошли",
    ENTER_EMAIL: "Введите e-mail",
    PASSWORD: "Пароль",
    ENTER_PASSWORD: "Введите пароль",
    LOG_IN: "Войти",
    ALREADY_EXISTS: "Пользователь с таким адресом эл. почты существует",
    SUCCESFULLY_REGISTERED:
      "Вы успешно зарегистрированы. Проверьте свой e-mail для подтверждения аккаунта",
    SUCCESS: "Успешно",
    SURNAME: "Фамилия",
    ENTER_SURNAME: "Введите фамилию",
    NAME: "Имя",
    ENTER_NAME: "Введите имя",
    REGISTER_: "Зарегистрироваться",
    ERROR_USER_DATA: "Ошибка в данных пользователя",
    USER_SUCCESSFULLY_DELETED: "Пользователь успешно удален",
    USER_NOT_FOUND: "Пользователь не найден",
    USER_SUCCESSFULLY_CHANGED: "Пользователь успешно изменен",
    SURE_DELETE_ACC: "Вы точно хотите удалить аккаунт? Вместе с этим вы удалите все его коллекции.",
    DELETE_ACCOUNT: "Удалить аккаунт",
    DELETING_ACCOUNT: "Удаление аккаунта",
    NEW_PASSWORD: "Новый пароль (По желанию)",
    ENTER_NEW_PASSWORD: "Введите новый пароль",
    CHANGE_DATA: "Изменить данные",
    DELETE_USER: "Удалить пользователя",
    MY_DATA: "Мои данные",
    LOGOUT: "Выйти",
    WRONG_PASSWORD: "Вы ввели неправильный пароль",
    DATA_SUCCESFULLY_CHANGED: "Данные успешно изменены",
    ERROR_IN_USER_DATA: "Ошибка в данных пользователя",
    SURE_DELETE_ACC_MY:
      "Вы точно хотите удалить аккаунт? Вместе с этим вы удалите все свои коллекции.",
    ENTER_NEW_SURNAME: "Введите новую фамилию",
    ENTER_NEW_NAME: "Введите новое имя",
    ENTER_NEW_EMAIL: "Введите новый email",
    ENTER_OLD_PASS: "Введите старый пароль",
    OLD_PASS: "Старый пароль (Обязательно)",
    NOTIFICATION: "Уведомление",
    ENTER_REQUEST: "Введите запрос",
    ERROR_REQUEST_BY_IDS: "Ошибка запроса по id пользователей",
    ERROR_REQUEST_SEARCH: "Ошибка запроса пользователей",
    SURNAME_AND_NAME: "Фамилия и имя",
    ENTER_SURNAME_NAME: "Введите фамилию и имя",
    MY_BOARDS: "Мои доски",
    DARK: "Темная",
    LIGHT: "Светлая",
    ADD_BOARD: "Добавить доску",
    CABINET: "Кабинет",
    MENU: "Меню",
    ERROR_404: "Ошибка 404 - Страница не найдена",
    ERROR_REQUEST: "Ошибка запроса",
    BOARD_ADDED: "Доска успешно добавлена",
    DESCRIPTION: "Описание (по желанию)",
    ENTER_DESCRIPTION: "Введите описание",
    BOARD_DELETED: "Доска успешно удалена",
    ERROR_BOARD_DELETING: "Ошибка в удалении доски",
    BOARD_LEFT: "Вы успешно покинули доску",
    ERROR_BOARD_LEAVING: "Ошибка в покидании доски",
    SURE_DELETE_BOARD:
      "Вы уверены, что хотите удалить эту доску? Вы потеряете все столбцы и задачи этой доски.",
    DELETE_BOARD: "Удалить доску",
    SURE_LEAVE_BOARD: "Вы уверены, что хотите покинуть эту доску?",
    LEAVE_BOARD: "Покинуть доску",
    CREATOR: "Создатель",
    BOARD_CHANGED: "Доска успешно изменена",
    CHANGE_BOARD: "Изменить доску",
    COLUMN_ADDED: "Столбец успешно добавлен",
    ADD_COLUMN: "Добавить столбец",
    COLUMN_CHANGED: "Столбец успешно изменен",
    CHANGE_COLUMN: "Изменить столбец",
    COLUMN_DELETED: "Столбец успешно удален",
    SURE_DELETE_COLUMN: "Вы уверены, что хотите удалить столбец? Вы потеряете все задачи столбца.",
    DELETE_COLUMN: "Удалить столбец",
    ERROR_CHANGING_TASK_COL: "Ошибка изменения столбца задачи",
    ERROR_CHANGING_COL_ORDER: "Ошибка изменения порядка столбцов",
    TASK_ADDED: "Задача успешно добавлена",
    ADD_TASK: "Добавить задачу",
    TASK_CHANGED: "Задача успешно изменена",
    CHANGE_TASK: "Изменить задачу",
    TASK_DELETED: "Задача успешно удалена",
    SURE_DELETE_TASK: "Вы уверены, что хотите удалить задачу?",
    DELETE_TASK: "Удалить задачу",
    MOVED: "Перемещено",
    CREATED: "Создано",
    USERS: "Польз.",
    ADD_USERS: "..."
  },
  {
    ERROR: "Error",
    ERROR_ACCESS_TOKEN: "Access token error",
    INPUT_DATA: "Input data",
    LOADING: "Loading...",
    LOGIN: "Log In",
    REGISTER: "Sign Up",
    INVALID_LOGIN: "You've entered invalid email or password",
    NO_ACCESS: "No access",
    SUCCESFULLY_ENTERED: "You've succesfully entered",
    ENTER_EMAIL: "Input e-mail",
    PASSWORD: "Password",
    ENTER_PASSWORD: "Input password",
    LOG_IN: "Log In",
    ALREADY_EXISTS: "User with that email already exists",
    SUCCESFULLY_REGISTERED: "You've succesfully registered. Check your e-mail for confirm letter",
    SUCCESS: "Success",
    SURNAME: "Surname",
    ENTER_SURNAME: "Input surname",
    NAME: "Name",
    ENTER_NAME: "Input name",
    REGISTER_: "Sign Up",
    ERROR_USER_DATA: "User data error",
    USER_SUCCESSFULLY_DELETED: "User successfully deleted",
    USER_NOT_FOUND: "User not found",
    USER_SUCCESSFULLY_CHANGED: "User successfully changed",
    SURE_DELETE_ACC:
      "Are you sure you want to delete an account? You will also delete all of his collections.",
    DELETE_ACCOUNT: "Delete an account",
    DELETING_ACCOUNT: "Account deleting",
    NEW_PASSWORD: "New password (Optional)",
    ENTER_NEW_PASSWORD: "Input new password",
    CHANGE_DATA: "Change data",
    DELETE_USER: "Delete user",
    MY_DATA: "My info",
    LOGOUT: "Log out",
    WRONG_PASSWORD: "You've entered wrong password",
    DATA_SUCCESFULLY_CHANGED: "Info succesfully changed",
    ERROR_IN_USER_DATA: "Error in user data",
    SURE_DELETE_ACC_MY:
      "Are you sure you want to delete an account? You will also delete all of your collections.",
    ENTER_NEW_SURNAME: "Input new surname",
    ENTER_NEW_NAME: "Input new name",
    ENTER_NEW_EMAIL: "Input new email",
    ENTER_OLD_PASS: "Input old password",
    OLD_PASS: "Old password (necessary)",
    NOTIFICATION: "Notification",
    ENTER_REQUEST: "Enter request",
    ERROR_REQUEST_BY_IDS: "Request by ids error",
    ERROR_REQUEST_SEARCH: "Request search error",
    SURNAME_AND_NAME: "Surname and name",
    ENTER_SURNAME_NAME: "Enter surname and name",
    MY_BOARDS: "My boards",
    DARK: "Dark",
    LIGHT: "Light",
    ADD_BOARD: "Add board",
    CABINET: "Cabinet",
    MENU: "Menu",
    ERROR_404: "Error 404 - Page not found",
    ERROR_REQUEST: "Request error",
    BOARD_ADDED: "Board succesfully added",
    DESCRIPTION: "Description (optional)",
    ENTER_DESCRIPTION: "Enter description",
    BOARD_DELETED: "Board deleted successfully",
    ERROR_BOARD_DELETING: "Error in board deleting",
    BOARD_LEFT: "Board left successfully",
    ERROR_BOARD_LEAVING: "Error in board leaving",
    SURE_DELETE_BOARD:
      "Are you sure you want delete this board? You will lost all your columns and tasks dedicated to this board.",
    DELETE_BOARD: "Delete board",
    SURE_LEAVE_BOARD: "Are you sure you want leave this board?",
    LEAVE_BOARD: "Leave board",
    CREATOR: "Creator",
    BOARD_CHANGED: "Board succesfully changed",
    CHANGE_BOARD: "Change board",
    COLUMN_ADDED: "Column added succesfully",
    ADD_COLUMN: "Add column",
    COLUMN_CHANGED: "Column changed succesfully",
    CHANGE_COLUMN: "Change column",
    COLUMN_DELETED: "Column deleted succesfully",
    SURE_DELETE_COLUMN:
      "Are you sure you want delete this column? You will lost all tasks dedicated to this column.",
    DELETE_COLUMN: "Delete column",
    ERROR_CHANGING_TASK_COL: "Error changing task column",
    ERROR_CHANGING_COL_ORDER: "Error changing column order",
    TASK_ADDED: "Task added succesfully",
    ADD_TASK: "Add task",
    TASK_CHANGED: "Task changed succesfully",
    CHANGE_TASK: "Change task",
    TASK_DELETED: "Task deleted succesfully",
    SURE_DELETE_TASK: "Are you sure you want delete this task?",
    DELETE_TASK: "Delete task",
    MOVED: "Moved",
    CREATED: "Created",
    USERS: "Users",
    ADD_USERS: "add users"
  }
]
