export const variables = {
    API_URL: "https://express-backend-trello.vercel.app/api",
    TOKEN_LOCALSTORAGE: "token",
    THEME_LOCALSTORAGE: "page_theme",
    LANGUAGE_LOCALSTORAGE: "page_language",
    USERID_LOCALSTORAGE: "user_id",
    BURGER_BREAKPOINT: 576,
    LANGUAGES: [
        {
            ERROR: 'Ошибка',
            ERROR_ACCESS_TOKEN: 'Ошибка токена доступа',
            INPUT_DATA: 'Введите данные',
            LOADING: 'Загрузка...',
            LOGIN: "Вход",
            REGISTER: 'Регистрация',
            INVALID_LOGIN: 'Вы ввели неправильный email или пароль',
            NO_ACCESS: 'Нет доступа',
            SUCCESFULLY_ENTERED: 'Вы успешно вошли',
            ENTER_EMAIL: 'Введите e-mail',
            PASSWORD: 'Пароль',
            ENTER_PASSWORD: 'Введите пароль',
            LOG_IN: 'Войти',
            ALREADY_EXISTS: 'Пользователь с таким адресом эл. почты существует',
            SUCCESFULLY_REGISTERED: 'Вы успешно зарегистрированы. Проверьте свой e-mail для подтверждения аккаунта',
            SUCCESS: 'Успешно',
            SURNAME: 'Фамилия',
            ENTER_SURNAME: 'Введите фамилию',
            NAME: 'Имя',
            ENTER_NAME: 'Введите имя',
            REGISTER_: 'Зарегистрироваться',
            ERROR_USER_DATA: 'Ошибка в данных пользователя',
            USER_SUCCESSFULLY_DELETED: 'Пользователь успешно удален',
            USER_NOT_FOUND: 'Пользователь не найден',
            USER_SUCCESSFULLY_CHANGED: 'Пользователь успешно изменен',
            SURE_DELETE_ACC: 'Вы точно хотите удалить аккаунт? Вместе с этим вы удалите все его коллекции.',
            DELETE_ACCOUNT: 'Удалить аккаунт',
            DELETING_ACCOUNT: 'Удаление аккаунта',
            ADMIN_MENU: 'Меню администратора',
            SELECTED_USER: 'Выбранный пользователь',
            ROLE: 'Роль',
            USER: 'Пользователь',
            ADMIN: 'Администратор',
            ACCESS: 'Доступ',
            NEW_PASSWORD: 'Новый пароль (По желанию)',
            ENTER_NEW_PASSWORD: 'Введите новый пароль',
            CHANGE_DATA: 'Изменить данные',
            DELETE_USER: 'Удалить пользователя',
            YES: 'Да',
            NO: 'Нет',
            RETURN_TO_MAIN: 'Вернуться на главную',
            MY_DATA: 'Мои данные',
            MY_COLLECTIONS: 'Мои коллекции',
            MY_COMMENTS: 'Мои комментарии',
            MY_REACTIONS: 'Мои реакции',
            LOGOUT: 'Выйти',
            WRONG_PASSWORD: 'Вы ввели неправильный пароль',
            DATA_SUCCESFULLY_CHANGED: 'Данные успешно изменены',
            ERROR_IN_USER_DATA: 'Ошибка в данных пользователя',
            SURE_DELETE_ACC_MY: 'Вы точно хотите удалить аккаунт? Вместе с этим вы удалите все свои коллекции.',
            ENTER_NEW_SURNAME: 'Введите новую фамилию',
            ENTER_NEW_NAME: 'Введите новое имя',
            ENTER_NEW_EMAIL: 'Введите новый email',
            ENTER_OLD_PASS: 'Введите старый пароль',
            OLD_PASS: 'Старый пароль (Обязательно)',
            NOTIFICATION: 'Уведомление',
            ENTER_REQUEST: 'Введите запрос',
            ERROR_REQUEST_BY_IDS: "Ошибка запроса по id пользователей",
            ERROR_REQUEST_SEARCH: "Ошибка запроса пользователей",
            SURNAME_AND_NAME: 'Фамилия и имя',
            ENTER_SURNAME_NAME:"Введите фамилию и имя"
        },
        {
            ERROR: 'Error',
            ERROR_ACCESS_TOKEN: 'Access token error',
            INPUT_DATA: 'Input data',
            LOADING: 'Loading...',
            LOGIN: "Log In",
            REGISTER: 'Sign Up',
            INVALID_LOGIN: 'You\'ve entered invalid email or password',
            NO_ACCESS: 'No access',
            SUCCESFULLY_ENTERED: 'You\'ve succesfully entered',
            ENTER_EMAIL: 'Input e-mail',
            PASSWORD: 'Password',
            ENTER_PASSWORD: 'Input password',
            LOG_IN: 'Log In',
            ALREADY_EXISTS: 'User with that email already exists',
            SUCCESFULLY_REGISTERED: "You've succesfully registered. Check your e-mail for confirm letter",
            SUCCESS: 'Success',
            SURNAME: 'Surname',
            ENTER_SURNAME: 'Input surname',
            NAME: 'Name',
            ENTER_NAME: 'Input name',
            REGISTER_: 'Sign Up',
            ERROR_USER_DATA: 'User data error',
            USER_SUCCESSFULLY_DELETED: 'User successfully deleted',
            USER_NOT_FOUND: 'User not found',
            USER_SUCCESSFULLY_CHANGED: 'User successfully changed',
            SURE_DELETE_ACC: 'Are you sure you want to delete an account? You will also delete all of his collections.',
            DELETE_ACCOUNT: 'Delete an account',
            DELETING_ACCOUNT: 'Account deleting',
            ADMIN_MENU: 'Admin menu',
            SELECTED_USER: 'Selected user',
            ROLE: 'Role',
            USER: 'User',
            ADMIN: 'Admin',
            ACCESS: 'Access',
            NEW_PASSWORD: 'New password (Optional)',
            ENTER_NEW_PASSWORD: 'Input new password',
            CHANGE_DATA: 'Change data',
            DELETE_USER: 'Delete user',
            YES: 'Yes',
            NO: 'No',
            RETURN_TO_MAIN: 'Return to main page',
            MY_DATA: 'My info',
            MY_COLLECTIONS: 'My collections',
            MY_COMMENTS: 'My comments',
            MY_REACTIONS: 'My reactions',
            LOGOUT: 'Log out',
            WRONG_PASSWORD: 'You\'ve entered wrong password',
            DATA_SUCCESFULLY_CHANGED: 'Info succesfully changed',
            ERROR_IN_USER_DATA: 'Error in user data',
            SURE_DELETE_ACC_MY: 'Are you sure you want to delete an account? You will also delete all of your collections.',
            ENTER_NEW_SURNAME: 'Input new surname',
            ENTER_NEW_NAME: 'Input new name',
            ENTER_NEW_EMAIL: 'Input new email',
            ENTER_OLD_PASS: 'Input old password',
            OLD_PASS: 'Old password (necessary)',
            NOTIFICATION: 'Notification',
            ENTER_REQUEST: 'Enter request',
            ERROR_REQUEST_BY_IDS: "Request by ids error",
            ERROR_REQUEST_SEARCH: "Request search error",
            SURNAME_AND_NAME: 'Surname and name',
            ENTER_SURNAME_NAME:"Enter surname and name"
        }
    ]
}

//UPD: пока что вставил 2 языка с финального проекта с курса, много чего совпадает
