export const variables = {
    API_URL: 'http://localhost:8080/api',
    TOKEN_LOCALSTORAGE: "token",
    THEME_LOCALSTORAGE: "page_theme",
    LANGUAGE_LOCALSTORAGE: "page_language",
    USERID_LOCALSTORAGE: "user_id",
    BURGER_BREAKPOINT: 576,
    LANGUAGES: [
        {
            ERROR_LOADING_COLLECTION_PHOTO: 'Ошибка загрузки фото коллекции',
            ERROR: 'Ошибка',
            ERROR_ACCESS_TOKEN: 'Ошибка токена доступа',
            COLLECTION_ADDED: 'Коллекция успешно добавлена',
            ERROR_ADDING_COLLECTION: 'Ошибка добавления коллекции',
            INPUT_DATA: 'Введите данные',
            RETURN_TO_THE_CABINET: 'Вернуться в личный кабинет',
            ADD_NEW_COLLECTION: 'Создание новой коллекции',
            COLLECTION_PHOTO: 'Фото коллекции',
            COLLECTION_NAME: 'Название коллекции',
            ENTER_COLLECTION_NAME: 'Введите название коллекции',
            COLLECTION_THEME: 'Тема коллекции',
            ENTER_COLLECTION_THEME: 'Введите тему коллекции',
            COLLECTION_DESCRIPTION: 'Описание в MarkDown (по желанию)',
            ENTER_COLLECTION_DESCRIPTION: 'Введите описание коллекции',
            ADD_COLLECTION_FIELDS: 'Добавьте поля коллекции',
            ADD_FIELD: 'Добавить поле',
            LOADING: 'Загрузка...',
            ADD_COLLECTION: 'Создать колллекцию',
            STRING: 'Строка',
            NUMBER: 'Число',
            DATE: 'Дата',
            BOOLEAN: 'Да/Нет',
            ENTER_FIELD_NAME: 'Введите название поля',
            CROP: 'Обрезать',
            MAX_PHOTO_SIZE: 'Максимальный размер фото - 5 МБ',
            LOGIN: "Вход",
            REGISTER: 'Регистрация',
            INVALID_LOGIN: 'Вы ввели неправильный email или пароль',
            NO_ACCESS: 'Нет доступа',
            SUCCESFULLY_ENTERED: 'Вы успешно вошли',
            ENTER_EMAIL: 'Введите e-mail',
            PASSWORD: 'Пароль',
            ENTER_PASSWORD: 'Введите пароль',
            LOG_IN: 'Войти',
            ALREADY_EXISTS: 'Пользователь с таким адресом эл. почты существует',
            SUCCESFULLY_REGISTERED: 'Вы успешно зарегистрированы',
            SUCCESS: 'Успешно',
            SURNAME: 'Фамилия',
            ENTER_SURNAME: 'Введите фамилию',
            NAME: 'Имя',
            ENTER_NAME: 'Введите имя',
            REGISTER_: 'Зарегистрироваться',
            ERROR_USER_DATA: 'Ошибка в данных пользователя',
            USER_SUCCESSFULLY_DELETED: 'Пользователь успешно удален',
            USER_NOT_FOUND: 'Пользователь не найден',
            USER_SUCCESSFULLY_CHANGED: 'Пользователь успешно изменен',
            SURE_DELETE_ACC: 'Вы точно хотите удалить аккаунт? Вместе с этим вы удалите все его коллекции.',
            DELETE_ACCOUNT: 'Удалить аккаунт',
            DELETING_ACCOUNT: 'Удаление аккаунта',
            ADMIN_MENU: 'Меню администратора',
            SELECTED_USER: 'Выбранный пользователь',
            ROLE: 'Роль',
            USER: 'Пользователь',
            ADMIN: 'Администратор',
            ACCESS: 'Доступ',
            NEW_PASSWORD: 'Новый пароль (По желанию)',
            ENTER_NEW_PASSWORD: 'Введите новый пароль',
            CHANGE_DATA: 'Изменить данные',
            DELETE_USER: 'Удалить пользователя',
            YES: 'Да',
            NO: 'Нет',
            RETURN_TO_MAIN: 'Вернуться на главную',
            MY_DATA: 'Мои данные',
            MY_COLLECTIONS: 'Мои коллекции',
            MY_COMMENTS: 'Мои комментарии',
            MY_REACTIONS: 'Мои реакции',
            LOGOUT: 'Выйти',
            NO_TAGS: 'Нет тегов',
            ERROR_LOAD_COLLECTIONS: 'Ошибка загрузки коллекций',
            CATEGORY: 'Категория:',
            ITEMS: 'Предметов:',
            FIELDS: 'Полей:',
            CREATED: 'Создано:',
            NO_YOUR_COMMENTS: 'Вы еще не оставляли комментариев',
            WRONG_PASSWORD: 'Вы ввели неправильный пароль',
            DATA_SUCCESFULLY_CHANGED: 'Данные успешно изменены',
            ERROR_IN_USER_DATA: 'Ошибка в данных пользователя',
            SURE_DELETE_ACC_MY: 'Вы точно хотите удалить аккаунт? Вместе с этим вы удалите все свои коллекции.',
            ENTER_NEW_SURNAME: 'Введите новую фамилию',
            ENTER_NEW_NAME: 'Введите новое имя',
            ENTER_NEW_EMAIL: 'Введите новый email',
            ENTER_OLD_PASS: 'Введите старый пароль',
            OLD_PASS: 'Старый пароль (Обязательно)',
            NO_YOUR_REACTIONS: 'Вы еще не оставляли реакций',
            COLLECTION_CHANGED: 'Коллекция успешно изменена',
            RETURN_TO_COLLECTION: 'Вернуться к коллекции',
            CHANGE_COLLECTION: 'Изменение коллекции',
            CHANGE_COLLECTION_: 'Изменить коллекцию',
            COLLECTION_NOT_FOUND: 'Коллекция не найдена',
            FIELDS_DONT_MATCH: 'Поля коллекции и предмета не совпадают',
            EMPTY_FIELDS: 'Присутствуют пустые поля',
            NO_ACCESS_ITEM: 'Нет доступа к предмету',
            ERROR_CHANGE_ITEM: 'Ошибка изменения предмета',
            RETURN_TO_ITEM: 'Вернуться к предмету',
            ITEM_CHANGING: 'Изменение предмета',
            ITEM_NAME: 'Название предмета',
            ENTER_ITEM_NAME: 'Введите название предмета',
            TAGS: 'Теги',
            ADD: 'Добавить',
            CHANGE_ITEM: 'Изменить предмет',
            ITEM_CHANGED: 'Предмет успешно изменен',
            ITEM_ADDING: 'Добавление предмета',
            ADD_TAGS: 'Добавьте теги',
            ADD_ITEM: 'Добавить предмет',
            ITEM_ADDED: 'Предмет успешно добавлен',
            ERROR_ADDING_ITEM: 'Ошибка добавления предмета',
            ENTER_TAG: "Введите тег",
            COLLECTION_DELETED: 'Коллекция успешно удалена',
            ERROR_DELETING_COLLECTION: 'Ошибка удаления коллекции',
            SURE_DELETE_COLLECTION: 'Вы точно хотите удалить коллекцию? Вместе с этим вы удалите все предметы этой коллекции.',
            DELETE_COLLECTION: 'Удалить коллекцию',
            COLLECTION_DELETING: 'Удаление коллекции',
            COLLECTION: 'Коллекция',
            CREATOR: 'Создатель:',
            NO_ITEMS_IN_COLLECTION: 'В этой коллекции пока нет предметов',
            ENTER_SEARCH: 'Введите запрос',
            CABINET: 'Личный кабинет',
            BIGGEST_COLLECTIONS: 'Самые большие коллекции',
            SHOW_MORE: 'Показать еще',
            COLLECTIONS_NOT_FOUND: 'Коллекции не найдены',
            LAST_ITEMS: 'Последние добавленные предметы',
            RECENT_TAGS: 'Недавние теги',
            ITEMS_NOT_FOUND: 'Предметы не найдены',
            ITEM_NOT_FOUND: 'Предмет не найден',
            COMMENT_ADDED: 'Комментарий успешно создан',
            ERROR_ADDING_COMMENT: 'Ошибка создания комментария',
            COMMENT_NOT_FOUND: 'Комментарий не найден',
            COMMENT_DELETED: 'Комментарий успешно удален',
            ERROR_DELETING_COMMENT: 'Ошибка удаления комментария',
            COMMENTS: 'Комментарии:',
            SEND: 'Отправить',
            ENTER_COMMENT: "Введите комментарий",
            NO_COMMENTS_ITEM: 'На этом предмете пока нет комментариев',
            ITEM_DELETED: 'Предмет успешно удален',
            ERROR_DELETING_ITEM: 'Ошибка удаления предмета',
            SURE_DELETE_ITEM: 'Вы точно хотите удалить предмет? Вместе с этим вы удалите все его комментарии и реакции.',
            LOG_TO_REACT: 'Войдите, чтобы ставить реакции',
            ITEM: 'Предмет',
            LIKE: 'Нравится',
            DISLIKE: 'Не нравится',
            DELETE_ITEM: 'Удалить предмет',
            DELETING_ITEM: 'Удаление предмета',
            GO_TO: 'Перейти',
            ERROR_404: 'Ошибка 404 - Страница не найдена',
            SEARCH_RESULTS: 'Результаты поиска по запросу:',
            NO_RESULTS: 'Результатов нет',
            NOTIFICATION: 'Уведомление'
        },
        {
            ERROR_LOADING_COLLECTION_PHOTO: 'Loading collection photo error',
            ERROR: 'Error',
            ERROR_ACCESS_TOKEN: 'Access token error',
            COLLECTION_ADDED: 'Collection succesfully added',
            ERROR_ADDING_COLLECTION: 'Adding collection error',
            INPUT_DATA: 'Input data',
            RETURN_TO_THE_CABINET: 'Return to the cabinet',
            ADD_NEW_COLLECTION: 'Add new collection',
            COLLECTION_PHOTO: 'Collection photo',
            COLLECTION_NAME: 'Collection name',
            ENTER_COLLECTION_NAME: 'Input collection name',
            COLLECTION_THEME: 'Collection theme',
            ENTER_COLLECTION_THEME: 'Input collection theme',
            COLLECTION_DESCRIPTION: 'Description in MarkDown (optional)',
            ENTER_COLLECTION_DESCRIPTION: 'Input collection description',
            ADD_COLLECTION_FIELDS: 'Add collection fields',
            ADD_FIELD: 'Add field',
            LOADING: 'Loading...',
            ADD_COLLECTION: 'Add collection',
            STRING: 'String',
            NUMBER: 'Number',
            DATE: 'Date',
            BOOLEAN: 'Yes/No',
            ENTER_FIELD_NAME: 'Input field name',
            CROP: 'Crop',
            MAX_PHOTO_SIZE: 'MAX PHOTO SIZE - 5 MB',
            LOGIN: "Log In",
            REGISTER: 'Sign Up',
            INVALID_LOGIN: 'You\'ve entered invalid email or password',
            NO_ACCESS: 'No access',
            SUCCESFULLY_ENTERED: 'You\'ve succesfully entered',
            ENTER_EMAIL: 'Input e-mail',
            PASSWORD: 'Password',
            ENTER_PASSWORD: 'Input password',
            LOG_IN: 'Log In',
            ALREADY_EXISTS: 'User with that email already exists',
            SUCCESFULLY_REGISTERED: 'You\'ve succesfully registered',
            SUCCESS: 'Success',
            SURNAME: 'Surname',
            ENTER_SURNAME: 'Input surname',
            NAME: 'Name',
            ENTER_NAME: 'Input name',
            REGISTER_: 'Sign Up',
            ERROR_USER_DATA: 'User data error',
            USER_SUCCESSFULLY_DELETED: 'User successfully deleted',
            USER_NOT_FOUND: 'User not found',
            USER_SUCCESSFULLY_CHANGED: 'User successfully changed',
            SURE_DELETE_ACC: 'Are you sure you want to delete an account? You will also delete all of his collections.',
            DELETE_ACCOUNT: 'Delete an account',
            DELETING_ACCOUNT: 'Account deleting',
            ADMIN_MENU: 'Admin menu',
            SELECTED_USER: 'Selected user',
            ROLE: 'Role',
            USER: 'User',
            ADMIN: 'Admin',
            ACCESS: 'Access',
            NEW_PASSWORD: 'New password (Optional)',
            ENTER_NEW_PASSWORD: 'Input new password',
            CHANGE_DATA: 'Change data',
            DELETE_USER: 'Delete user',
            YES: 'Yes',
            NO: 'No',
            RETURN_TO_MAIN: 'Return to main page',
            MY_DATA: 'My info',
            MY_COLLECTIONS: 'My collections',
            MY_COMMENTS: 'My comments',
            MY_REACTIONS: 'My reactions',
            LOGOUT: 'Log out',
            NO_TAGS: 'No tags',
            ERROR_LOAD_COLLECTIONS: 'Error collections load',
            CATEGORY: 'Category:',
            ITEMS: 'Items:',
            FIELDS: 'Fields:',
            CREATED: 'Created:',
            NO_YOUR_COMMENTS: 'There are no your comments yet',
            WRONG_PASSWORD: 'You\'ve entered wrong password',
            DATA_SUCCESFULLY_CHANGED: 'Info succesfully changed',
            ERROR_IN_USER_DATA: 'Error in user data',
            SURE_DELETE_ACC_MY: 'Are you sure you want to delete an account? You will also delete all of your collections.',
            ENTER_NEW_SURNAME: 'Input new surname',
            ENTER_NEW_NAME: 'Input new name',
            ENTER_NEW_EMAIL: 'Input new email',
            ENTER_OLD_PASS: 'Input old password',
            OLD_PASS: 'Old password (necessary)',
            NO_YOUR_REACTIONS: 'There are no your reactions yet',
            COLLECTION_CHANGED: 'Collection succesfully changed',
            RETURN_TO_COLLECTION: 'Return to the collection',
            CHANGE_COLLECTION: 'Change collection',
            CHANGE_COLLECTION_: 'Change collection',
            COLLECTION_NOT_FOUND: 'Collection not found',
            FIELDS_DONT_MATCH: 'Collection and item fields don\'t match',
            EMPTY_FIELDS: 'There are an empty fields',
            NO_ACCESS_ITEM: 'No access to item',
            ERROR_CHANGE_ITEM: 'Item changing error',
            RETURN_TO_ITEM: 'Return to the item',
            ITEM_CHANGING: 'Change item',
            ITEM_NAME: 'Item name',
            ENTER_ITEM_NAME: 'Input item name',
            TAGS: 'Tags',
            ADD: 'Add',
            CHANGE_ITEM: 'Change item',
            ITEM_CHANGED: 'Item successfully changed',
            ITEM_ADDING: 'Add item',
            ADD_TAGS: 'Add tags',
            ADD_ITEM: 'Add item',
            ITEM_ADDED: 'Item succesfully added',
            ERROR_ADDING_ITEM: 'Item adding error',
            ENTER_TAG: "Input tag",
            COLLECTION_DELETED: 'Collection successfylly deleted',
            ERROR_DELETING_COLLECTION: 'Deleting collection error',
            SURE_DELETE_COLLECTION: 'Are you sure you want to delete a collection? You will also delete all of items in that collection.',
            DELETE_COLLECTION: 'Delete collection',
            COLLECTION_DELETING: 'Delete collection',
            COLLECTION: 'Collection',
            CREATOR: 'Creator:',
            NO_ITEMS_IN_COLLECTION: 'There are no items in than collection',
            ENTER_SEARCH: 'Search',
            CABINET: 'Cabinet',
            BIGGEST_COLLECTIONS: 'The most biggest collections',
            SHOW_MORE: 'Show more',
            COLLECTIONS_NOT_FOUND: 'Collections not found',
            LAST_ITEMS: 'Last added items',
            RECENT_TAGS: 'Recent tags',
            ITEMS_NOT_FOUND: 'Items not found',
            ITEM_NOT_FOUND: 'Item not found',
            COMMENT_ADDED: 'Comment successfully added',
            ERROR_ADDING_COMMENT: 'Add comment error',
            COMMENT_NOT_FOUND: 'Comment not found',
            COMMENT_DELETED: 'Comment successfully deleted',
            ERROR_DELETING_COMMENT: 'Delete comment error',
            COMMENTS: 'Comments:',
            SEND: 'Send',
            ENTER_COMMENT: "Input comment",
            NO_COMMENTS_ITEM: 'There are no comments yet',
            ITEM_DELETED: 'Item successfully deleted',
            ERROR_DELETING_ITEM: 'Delete item error',
            SURE_DELETE_ITEM: 'Are you sure you want to delete an item? You will also delete all of the comments and reactions of that item.',
            LOG_TO_REACT: 'Log in to react on item',
            ITEM: 'Item',
            LIKE: 'Like',
            DISLIKE: 'Dislike',
            DELETE_ITEM: 'Delete item',
            DELETING_ITEM: 'Delete item',
            GO_TO: 'Go to',
            ERROR_404: 'Error 404 - Page not found',
            SEARCH_RESULTS: 'Search results:',
            NO_RESULTS: 'No results',
            NOTIFICATION: 'Notification'
        }
    ]
}